const owner="kindgommangaraw",repo="kindgommangaraw.github.io",branch="main",KEY="mr_admin_token";
const $=id=>document.getElementById(id);
function msg(x){$("status").textContent=x}
function auth(){const t=sessionStorage.getItem(KEY)||localStorage.getItem(KEY)||$("token")?.value.trim();if(!t)throw Error("Connect GitHub first.");return t}
async function gh(path,options={}){const r=await fetch("https://api.github.com/repos/"+owner+"/"+repo+"/contents/"+path,{...options,headers:{Accept:"application/vnd.github+json",Authorization:"Bearer "+auth(),"X-GitHub-Api-Version":"2022-11-28",...(options.headers||{})}});if(!r.ok){let d={};try{d=await r.json()}catch{}throw Error(d.message||("GitHub API HTTP "+r.status))}return r.json()}
const b64=s=>btoa(unescape(encodeURIComponent(s)));
const decode=s=>decodeURIComponent(escape(atob(s.replace(/\n/g,""))));
const fileB64=async f=>{const a=await f.arrayBuffer(),u=new Uint8Array(a);let s="";for(let i=0;i<u.length;i+=0x8000)s+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(s)};
async function put(path,content,message,binary=false){let sha;try{sha=(await gh(path)).sha}catch(e){if(!String(e.message).includes("Not Found"))throw e}const body={message,content:binary?content:b64(content),branch};if(sha)body.sha=sha;return gh(path,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}
async function readJson(path){const x=await gh(path);return{data:JSON.parse(decode(x.content)),sha:x.sha}}
async function publicJson(path){const r=await fetch("../"+path+"?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("Unable to load "+path+" (HTTP "+r.status+")");return r.json()}
async function getChapters(){try{return await publicJson("data/chapters.json")}catch(publicError){try{const x=await gh("data/chapters.json");return JSON.parse(decode(x.content))}catch(apiError){throw Error("Chapter list could not be loaded. Public: "+publicError.message+" | GitHub: "+apiError.message)}}}
async function listDir(path){return gh(path)}
async function removeFile(path,sha){return gh(path,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:"Admin: remove chapter image",sha,branch})})}
async function removeDirFiles(path){let old=[];try{old=await listDir(path)}catch(e){if(String(e.message).includes("Not Found"))return;throw e}for(const f of old){if(f.type==="file")await removeFile(f.path,f.sha)}}
let chapterCache=[];
function populateChapterSelect(chapters){const s=$("chapterSelect");s.innerHTML='<option value="">Select chapter to edit</option>';(chapters||[]).forEach(c=>{const o=document.createElement("option");o.value=c.slug;o.textContent=(c.manga_title||c.manga_slug||"Manga")+" — "+(c.title||"Chapter "+c.number);s.appendChild(o)});}
async function loadChapters(){const data=await getChapters();chapterCache=Array.isArray(data.chapters)?data.chapters:[];populateChapterSelect(chapterCache);if(chapterCache.length){const c=chapterCache[0];$("chapterSelect").value=c.slug;fill(c);msg(chapterCache.length+" chapter(s) loaded. "+c.title+" ready to edit.")}else msg("No chapters found in data/chapters.json.")}
function fill(c){$("cslug").value=c.slug||"";$("mangaSlug").value=c.manga_slug||"";$("number").value=c.number||"";$("chapterTitle").value=c.title||"";$("pages").value=JSON.stringify(c.pages||[],null,2)}
$("refreshChapters").onclick=async()=>{try{await loadChapters()}catch(e){msg("❌ "+e.message)}};
$("chapterSelect").onchange=()=>{const c=chapterCache.find(x=>x.slug===$("chapterSelect").value);if(c){fill(c);msg("✓ "+c.title+" loaded for editing.")}else fill({});};
$("uploadImages").onclick=async()=>{try{const slug=$("cslug").value.trim(),mangaSlug=$("mangaSlug").value.trim(),number=$("number").value.trim();if(!slug||!mangaSlug||!number)throw Error("Chapter slug, manga slug and chapter number are required.");const files=[...$("imageFiles").files];if(!files.length)throw Error("Select chapter images first.");files.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:"base"}));const dir="chapter-images/"+mangaSlug+"/chapter-"+number+"/";const legacyDir="chapter-images/"+slug+"/";msg("Uploading images to "+dir+" …");await removeDirFiles(dir);if(legacyDir!==dir)await removeDirFiles(legacyDir);const pages=[];for(let i=0;i<files.length;i++){const f=files[i],ext=(f.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",name=String(i+1).padStart(3,"0")+"."+ext,path=dir+name;msg("Uploading image "+(i+1)+"/"+files.length+" …");await put(path,await fileB64(f),"Admin: upload chapter image",true);pages.push("/"+path)}$("pages").value=JSON.stringify(pages,null,2);msg("✓ "+files.length+" image(s) uploaded. ALT text: "+($("chapterTitle").value.trim()||("Chapter "+number)));}catch(e){msg("❌ Image upload failed: "+e.message)}};
$("chapter").onclick=async()=>{try{const {data}=await readJson("data/chapters.json");let pages;try{pages=JSON.parse($("pages").value||"[]")}catch{throw Error("Pages JSON is invalid.")}const chapterName=$("chapterTitle").value.trim()||("Chapter "+$("number").value.trim());const item={slug:$("cslug").value.trim(),manga_slug:$("mangaSlug").value.trim(),number:$("number").value.trim(),title:chapterName,pages,alt_text:chapterName};if(!item.slug||!item.manga_slug)throw Error("Chapter slug and manga slug are required.");const i=data.chapters.findIndex(x=>x.slug===item.slug);if(i<0)data.chapters.push(item);else data.chapters[i]={...data.chapters[i],...item};await put("data/chapters.json",JSON.stringify(data,null,2),"Admin: save chapter");await loadChapters();$("chapterSelect").value=item.slug;fill(item);msg("✓ Chapter saved. Every image should use this full chapter name as ALT text in the viewer.")}catch(e){msg("❌ Save failed: "+e.message)}};
$("deleteChapter").onclick=async()=>{try{const slug=$("cslug").value.trim(),mangaSlug=$("mangaSlug").value.trim(),number=$("number").value.trim();if(!slug||!confirm("Delete this chapter record and all its images?"))return;await removeDirFiles("chapter-images/"+mangaSlug+"/chapter-"+number+"/");await removeDirFiles("chapter-images/"+slug+"/");const {data}=await readJson("data/chapters.json");data.chapters=data.chapters.filter(x=>x.slug!==slug);await put("data/chapters.json",JSON.stringify(data,null,2),"Admin: delete chapter");fill({});await loadChapters();msg("Chapter and its images deleted.")}catch(e){msg("❌ Delete failed: "+e.message)}};
$("manga").onclick=async()=>{try{const {data}=await readJson("data/manga.json");const item={slug:$("slug").value.trim(),title:$("title").value.trim(),country:$("country").value.trim().toUpperCase(),author:$("author").value.trim(),cover:$("cover").value.trim(),description:$("description").value.trim()};if(!item.slug||!item.title)throw Error("Slug and title are required.");const i=data.manga.findIndex(x=>x.slug===item.slug);if(i<0)data.manga.push(item);else data.manga[i]={...data.manga[i],...item};await put("data/manga.json",JSON.stringify(data,null,2),"Admin: save manga");msg("Manga saved to GitHub.")}catch(e){msg("❌ Manga save failed: "+e.message)}};
loadChapters().catch(e=>msg("Chapter list: "+e.message));
